/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JnsBS1GcmBR
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Link } from "@remix-run/react";
import React from "react";

const DesktopHeader = () => {
  return (
    <header className="w-full bg-gray-900 py-4 shadow-lg">
      <div className="container relative mx-auto flex max-w-7xl items-center justify-between px-6">
        <Link className="flex items-center" to="#">
          <MountainIcon className="h-8 w-8 text-white" />
          <span className="ml-2 text-lg font-bold text-white">Acme Inc.</span>
        </Link>
        <nav className="flex">nav</nav>
      </div>
    </header>
  );
};
export default DesktopHeader;

const MountainIcon = (props: React.SVGProps<SVGSVGElement>) => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
};
